mad-login3
codemaster80/MAD-Project pull request #103
Opened 2024-12-29 21:04 UTC by codemaster80

2024-12-30 10:50 UTC, kyklospi requested changes

2024-12-30 10:50 UTC, kyklospi commented on app/src/main/java/org/dieschnittstelle/mobile/android/skeleton/MainActivity.java
> +    private User user = new User("", "");
das soll man nicht hier initialisieren. sondern während `onCreate()` wie bei Task-Objekt in `TaskDetailViewActivity` Klasse

2024-12-30 10:50 UTC, kyklospi commented on app/src/main/java/org/dieschnittstelle/mobile/android/skeleton/MainActivity.java
>          setContentView(R.layout.activity_main);
das sollen wir löschen, da wir jetzt `setContentView() `durch DataBinding machen

2024-12-30 10:50 UTC, kyklospi commented on app/src/main/java/org/dieschnittstelle/mobile/android/skeleton/TaskApplication.java
> +        this.userDatabaseOperation = new LocalUserDatabaseOperation(this);
hier hast du immer noch LocalUserDatabase initialisiert. Das kannst du auskommentieren. da wir ja nach https://github.com/codemaster80/MAD-Project/issues/22 nur auf Remote zugreifen muss

2024-12-30 10:50 UTC, kyklospi commented on app/src/main/java/org/dieschnittstelle/mobile/android/skeleton/model/UserTypeConverter.java
> +public class UserTypeConverter {
Sowie bei Task-Klasse, brauchen wir diese Konvertierungsklasse nicht.

2024-12-30 10:50 UTC, kyklospi commented on app/src/main/java/org/dieschnittstelle/mobile/android/skeleton/model/LocalUserDatabaseOperation.java
> +    @TypeConverters(UserTypeConverter.class)
diese kannst du löschen. Erklärung in nachste Kommentar

2024-12-30 10:50 UTC, kyklospi commented on app/src/main/java/org/dieschnittstelle/mobile/android/skeleton/viewmodel/MainViewModel.java
> +        private MutableLiveData<String> loginLiveData = new MutableLiveData<>("initial");
siehe TaskDetailViewModel. Hier soll wie ProceesingState implementiert werden.

```suggestion
        public enum LoginState {INVALID_EMAIL, WRONG_PASSWORD, AUTHENTICATION_SUCCESS, AUTHENTICATION_FAIL}
        private MutableLiveData<LoginState> loginState = new MutableLiveData<>();
```

2024-12-30 10:50 UTC, kyklospi commented on app/src/main/java/org/dieschnittstelle/mobile/android/skeleton/MainActivity.java
> +        });
siehe `TaskListViewActivity` Klasse für `ProcessingState` als Referenz

```suggestion
        viewModel.getLoginState().observe(this, this::handleUserLoginState);
```

2024-12-30 10:50 UTC, kyklospi commented on app/src/main/java/org/dieschnittstelle/mobile/android/skeleton/MainActivity.java
>      }
hier kann man die Methode für LoginState Bedingung schreiben

```suggestion
    private void handleUserLoginState(MainViewModel.LoginState loginState) {
            switch (loginState) {
                case INVALID_EMAIL:
                    showPersistentMessage(getString(R.string.login_username_error));
                    break;
                case WRONG_PASSWORD:
                    Snackbar.make(findViewById(R.id.rootView), getString(R.string.login_password_not_allowed), Snackbar.LENGTH_SHORT).show();
                    break;
                case AUTHENTICATION_FAIL:
                    showPersistentMessage(getString(R.string.login_authentication_failed));
                    break;
                case AUTHENTICATION_SUCCESS:
                    Intent callTaskListViewIntent = new Intent(this, TaskListViewActivity.class);
                    startActivity(callTaskListViewIntent);
                    this.finish();
                    break;
                default:
                    break;
            }
    }
```

2024-12-30 10:50 UTC, kyklospi commented on app/src/main/res/layout/activity_main.xml
> +            android:id="@+id/editTextTextPassword"
vertippt bei `editTextTextPassword`. soll `editTextPassword` sein

2024-12-30 10:50 UTC, kyklospi commented on app/src/main/res/values/strings.xml
> +    <string name="login_password_not_allowed">Password must meet the following requirements - max. 6 digits</string>
Laut https://github.com/codemaster80/MAD-Project/issues/19 es muss genau 6 Ziffern sein und nicht max 6 Ziffern

2024-12-30 14:21 UTC, codemaster80 commented on app/src/main/java/org/dieschnittstelle/mobile/android/skeleton/MainActivity.java
>      }
Sehr übersichtlich

2024-12-30 22:20 UTC, kyklospi commented on app/src/main/java/org/dieschnittstelle/mobile/android/skeleton/model/LocalUserDatabaseOperation.java
> +        return false;
```suggestion
        User user = new User();
        user.setId(id);
        userDatabase.getDao().deleteUser(user);
        return true;
```

2024-12-30 22:20 UTC, kyklospi commented on app/src/main/java/org/dieschnittstelle/mobile/android/skeleton/viewmodel/MainViewModel.java
> +        INVALID_EMAIL, WRONG_PASSWORD, AUTHENTICATION_SUCCESS, AUTHENTICATION_FAIL
weil, die Email- und Password-Überprüfung läuft vor Betätigung des Login, brauchen wir den Status `INVALID_EMAIL` und `WRONG_PASSWORD` nicht mehr

2024-12-30 22:20 UTC, kyklospi commented on app/src/main/java/org/dieschnittstelle/mobile/android/skeleton/MainActivity.java
> +                case WRONG_PASSWORD:
wir brauchen den Status `INVALID_EMAIL` und `WRONG_PASSWORD` nicht mehr

2024-12-30 22:20 UTC, kyklospi commented on app/src/main/java/org/dieschnittstelle/mobile/android/skeleton/viewmodel/MainViewModel.java
> +        if (!(android.util.Patterns.EMAIL_ADDRESS.matcher(user.getEmail()).matches())) {
es fehlt davor noch die Überprüfung ob der Benutzer Enter oder tab drückt (siehe `TaskViewModel`)

```suggestion
        if (keyId == EditorInfo.IME_ACTION_NEXT || keyId == EditorInfo.IME_ACTION_DONE) {
            if (!(android.util.Patterns.EMAIL_ADDRESS.matcher(user.getEmail()).matches())) {...}
        }
```

2024-12-30 22:20 UTC, kyklospi commented on app/src/main/java/org/dieschnittstelle/mobile/android/skeleton/viewmodel/MainViewModel.java
> +        if (!(pwdCheck)) {
es fehlt davor noch die Überprüfung ob der Benutzer Enter oder tab drückt (siehe TaskViewModel)

```suggestion
        if (keyId == EditorInfo.IME_ACTION_NEXT || keyId == EditorInfo.IME_ACTION_DONE) {
            if (!(pwdCheck)) {...}
        }

```

2024-12-30 22:20 UTC, kyklospi commented on app/src/main/res/values/strings.xml
> +    <string name="login_password_not_allowed">Password must meet the following requirements - 6 digits</string>
`login_username_error` und `login_password_not_allowed` brauchen wir nicht mehr

2024-12-31 09:26 UTC, codemaster80 commented on app/src/main/java/org/dieschnittstelle/mobile/android/skeleton/viewmodel/MainViewModel.java
> +        INVALID_EMAIL, WRONG_PASSWORD, AUTHENTICATION_SUCCESS, AUTHENTICATION_FAIL
Entfernt

2024-12-31 09:26 UTC, codemaster80 commented on app/src/main/java/org/dieschnittstelle/mobile/android/skeleton/MainActivity.java
> +                case WRONG_PASSWORD:
Entfernt

2024-12-31 09:27 UTC, codemaster80 commented on app/src/main/java/org/dieschnittstelle/mobile/android/skeleton/viewmodel/MainViewModel.java
> +        if (!(android.util.Patterns.EMAIL_ADDRESS.matcher(user.getEmail()).matches())) {
Bin ich noch dran

2024-12-31 09:27 UTC, codemaster80 commented on app/src/main/res/values/strings.xml
> +    <string name="login_password_not_allowed">Password must meet the following requirements - 6 digits</string>
Entfernt

2024-12-31 09:27 UTC, closed without merging